# Generated by Django 4.1.3 on 2023-01-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muallif',
            name='kitob_soni',
            field=models.PositiveSmallIntegerField(default=12),
            preserve_default=False,
        ),
    ]
