# Generated by Django 4.1.3 on 2023-01-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_muallif_kitob_soni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='bitiruvchi',
            field=models.BooleanField(default=False),
        ),
    ]
